# -*- coding: utf-8 -*-
"""backtesting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkDBuYTUIf1pMqwe2t6zyEKLgZbk-RLO
"""

!pip install yfinance pandas numpy matplotlib scipy -q

TICKERS = [
    # 8 Defense Stocks
    'LMT', 'RTX', 'NOC', 'GD', 'BA', 'HII', 'LHX', 'LDOS',
    # 4 Defense ETFs
    'ITA', 'XAR', 'PPA', 'DFEN'
]
START_DATE   = '2018-01-01'
END_DATE     = None          # None = today

# GARCH-proxy signal parameters
VOL_WINDOW   = 20            # rolling window (days) to estimate realised vol
VOL_THRESH   = 0.25          # annualised vol threshold — above = go flat
INITIAL_CASH = 10_000

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings
warnings.filterwarnings('ignore')

def backtest(ticker):
    print(f'\n=== {ticker} ===')

    df = yf.download(ticker, start=START_DATE, end=END_DATE,
                     auto_adjust=True, progress=False)
    if df.empty:
        print('  No data, skipping.')
        return {}

    df = df[['Close']].copy()
    df['Return'] = df['Close'].pct_change()

    # ── GARCH-proxy: rolling realised volatility (annualised) ──
    df['RealVol'] = df['Return'].rolling(VOL_WINDOW).std() * np.sqrt(252)

    # ── Signal: 1 = long (low vol), 0 = flat (high vol) ────────
    # Shift by 1 so we trade on yesterday's signal (no lookahead)
    df['Signal']   = (df['RealVol'] < VOL_THRESH).astype(int)
    df['Position'] = df['Signal'].shift(1).fillna(0)

    df.dropna(inplace=True)

    # ── Returns ─────────────────────────────────────────────────
    df['Strategy_Return'] = df['Position'] * df['Return']
    df['Market_Equity']   = (1 + df['Return']).cumprod()          * INITIAL_CASH
    df['Strategy_Equity'] = (1 + df['Strategy_Return']).cumprod() * INITIAL_CASH

    # ── Metrics ──────────────────────────────────────────────────
    n_years   = len(df) / 252
    total_ret = df['Strategy_Equity'].iloc[-1] / INITIAL_CASH - 1
    cagr      = (1 + total_ret) ** (1 / n_years) - 1
    sr        = df['Strategy_Return']
    sharpe    = (sr.mean() / sr.std()) * np.sqrt(252) if sr.std() != 0 else 0
    roll_max  = df['Strategy_Equity'].cummax()
    max_dd    = ((df['Strategy_Equity'] - roll_max) / roll_max).min()
    pct_in    = df['Position'].mean()

    metrics = {
        'Ticker':         ticker,
        'Total Return':   f'{total_ret:.2%}',
        'CAGR':           f'{cagr:.2%}',
        'Sharpe Ratio':   f'{sharpe:.2f}',
        'Max Drawdown':   f'{max_dd:.2%}',
        'Time in Market': f'{pct_in:.1%}',
        'Final Equity':   f'${df["Strategy_Equity"].iloc[-1]:,.2f}',
    }

    for k, v in metrics.items():
        print(f'  {k:<16}: {v}')

    # ── Plot ─────────────────────────────────────────────────────
    fig = plt.figure(figsize=(13, 9))
    gs  = gridspec.GridSpec(3, 1, hspace=0.4)
    fig.suptitle(f'{ticker} — GARCH Vol Signal Backtest', fontsize=14, fontweight='bold')

    # Panel 1: Price
    ax0 = fig.add_subplot(gs[0])
    ax0.plot(df.index, df['Close'], color='#424242', lw=1)
    ax0.set_ylabel('Price ($)')
    ax0.set_title('Price', fontsize=10)
    ax0.grid(alpha=0.3)

    # Panel 2: Rolling vol + threshold
    ax1 = fig.add_subplot(gs[1])
    ax1.plot(df.index, df['RealVol'], color='#2196F3', lw=1, label='Realised Vol')
    ax1.axhline(VOL_THRESH, color='red', linestyle='--', lw=0.9, label=f'Threshold ({VOL_THRESH})')
    ax1.fill_between(df.index, df['RealVol'], VOL_THRESH,
                     where=(df['RealVol'] > VOL_THRESH),
                     color='red', alpha=0.15, label='High Vol (flat)')
    ax1.set_ylabel('Ann. Vol')
    ax1.set_title(f'{VOL_WINDOW}-Day Realised Vol vs Threshold', fontsize=10)
    ax1.legend(fontsize=8)
    ax1.grid(alpha=0.3)

    # Panel 3: Equity curves
    ax2 = fig.add_subplot(gs[2])
    ax2.plot(df.index, df['Strategy_Equity'], color='#4CAF50', lw=1.5, label='GARCH Strategy')
    ax2.plot(df.index, df['Market_Equity'],   color='#9C27B0', lw=1.5,
             linestyle='--', label='Buy & Hold')
    ax2.set_ylabel('Portfolio ($)')
    ax2.set_xlabel('Date')
    ax2.set_title('Equity Curve', fontsize=10)
    ax2.legend(fontsize=8)
    ax2.grid(alpha=0.3)

    plt.show()
    return metrics

all_metrics = [backtest(t) for t in TICKERS]

summary = pd.DataFrame([m for m in all_metrics if m])
print('\n========== PORTFOLIO SUMMARY ==========')
display(summary)